---
title: "Assignment2"
author: "Sandra Fogg"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
#Load Packages
library(ggplot2)
library(tidyverse)
```


```{r, echo=FALSE}
#Create a data frame
gas_df <- read_csv("Gas_Data.csv")
gas_df
```
###Create and graph demand curves, supply curve, and marginal external cost
```{r, echo=FALSE}


#Create demand curve for High and Low
demand_high <- ggplot(gas_df, aes(x = Q_Low_Gallons_per_Day, y = Price_Dollars)) + 
  geom_line(color = "#0073D9", size = 1) + 
  theme_classic() 
demand_high



#Create a linear regression
demand_high_lm <- lm(Price_Dollars ~ gas_df$Q_High_Gallons_per_Day, data = gas_df)
demand_high_lm

demand_low_lm <- lm(Price_Dollars ~ gas_df$Q_Low_Gallons_per_Day, data = gas_df)
demand_low_lm



#Set Coefficients

#High Demand Coefficients
demand_high_lm$coefficients
bh = demand_high_lm$coefficients[1]
mh = (demand_high_lm$coefficients[2])

#High Demand Equation
#ph = bh - mh(q)
#ph = 23.3914418-0.0001297(q)

qhighA <- (1/mh) # 1/slope or m for high income
qhighB <- (bh/-mh) # intercept or b/ - slope or m for high income

#Low Demand Coefficients
demand_low_lm$coefficients
bl = demand_low_lm$coefficients[1]
ml = (demand_low_lm$coefficients[2])

#Low Demand Equation
#pl = bl - ml(q)
#pl = 21.9908534-0.0001355(q)

qlowA <- (1/ml) # 1/slope or m for low income
qlowB <- (bl/-ml) # intercept or b/ - slope or m for low income



#Make Demand Curves
demand_eq_high <- function(q) {23.3914418-0.0001297*q}
demand_eq_low <- function(q) {21.9908534-0.0001355*q}



#Find aggregate demands separately for quantity
Q_aggb<- qlowB + qhighB # aggregate for intercept
Q_aggm<- qlowA + qhighA # aggregate for slope



#Find aggregate demand separately for price
P_aggb<- -Q_aggb/Q_aggm # aggregate for intercept
P_aggb
P_aggm<- 1/Q_aggm # aggregate for slope
P_aggm
p_aggregate <- function(p) {(P_aggb+P_aggm*p)}


# Find aggregate demand curve
q_aggregate <- function(q){P_aggb+P_aggm*q}



#Find MPC (supply curve) with price, $5.00
supply<- 5/((5-P_aggb)/P_aggm)
supply
supplym 



# Find marginal external cost
mec <- function(y) {2}



# List out functions
demand_eq_highgph <- function(q) {23.3914418-0.0001297*q}
demand_eq_lowgph <- function(q) {21.9908534-0.0001355*q}
mpcgph <- function(q) {supply*q}
mecgph <- function(y) {2}
q_aggregategph <- function(q){P_aggb+P_aggm*q}



# Graph curves
opt<- data.frame(x = c(0:267217.1), y = c(5))
x<- 70000:500000
demand_gph <- ggplot(data.frame(x = c(70000:400000)), aes(x=x))+
  stat_function(fun=mpcgph, geom = "line", color ="darkolivegreen3") +
  stat_function(fun=demand_eq_highgph, geom="line", color ="red3") +
  stat_function(fun=demand_eq_lowgph, geom="line", color ="goldenrod1") +
  stat_function(fun=q_aggregategph, geom = "line", color ="darkorange3") +
  stat_function(fun=mecgph, geom = "line", color ="chartreuse4") +
  xlab("\nQuantity (Gallons per Day)")+
  ylab("Price ($USD)\n")+
  ggtitle("Gas Market Under the Status Quo \n")+
  scale_y_continuous(limits = c(0,25), expand = c(0,0))+
  scale_x_continuous(limits = c(0,400000), expand = c(0,0), breaks = seq(0, 400000, 50000)) +
  theme_classic()

demand_gph
```

###Calculate the consumer benefits
```{r}
#Determine the aggregate consumer benefit

#Determine the market equilibrium point, when aggregate demand = supply
#At equilibrium: p = $5.00, q = 267217.062558
### 

#Aggregate equation =
#Q = 267217.062558
#Y intercept of agg demand
q_aggregategph(0)
# = 22.70661


#Double check the area using shapes
agg_height_cs <- 22.70661 - 5
agg_base_cs <- 267217.062558
aggregate_cs_geom <- (1/2)*agg_base_cs*agg_height_cs 
aggregate_cs
# = $2365754

```


###Calculate the produce benefits
```{r}
agg_height_ps <- 5
agg_base_ps <- 267217.062558
aggregate_ps_geom <- (1/2)*agg_height_ps*agg_base_ps
aggregate_ps_geom
# = $668042.7
```

###Calculate the environmental cost
```{r}
ec_height <- 2
ec_base <- 267217.062558
ec_geom <- ec_height*ec_base
ec_geom
# = $534434.1
```

##Question 2
###Determine the distribution of benefits
```{r}
# Find q for high income at $5.00
#ph <- 23.3914418-0.0001297*(q)
# 5 = 23.3914418-0.0001297*(q)
q_at_equil_h <- (5-23.3914418)/(-0.0001297)
q_at_equil_h
#q = 141799.9
demand_eq_high(141799.9)
#4.999995 ~ $5.00 check

#Calculate the high demand at equilibrium
height_equil_h <- 23.3914418 - 5
base_equil_h <-141799.9
cs_equil_h <- (1/2)*height_equil_h*base_equil_h 
cs_equil_h
# = $1303952


#Find q for low income at $5.00
#pl <- 21.9908534-0.0001355*q
#5 = 21.9908534-0.0001355*q
q_at_equil_l <- (5-21.9908534)/(-0.0001355)
q_at_equil_l

height_equil_l <- 21.9908534 - 5
base_equil_l <- 125393.8
cs_equil_l <- (1/2)*height_equil_l*base_equil_l 
cs_equil_l
# =  $1065274


# Find the difference in benefits
benefits_difference = 1303952-1065274
benefits_difference
# = $238678
```
```{r}
#Adding a $0.50 tax/gallon

#MPC (supply) curve changes
#Originial -> MPC = 1.871138e-05*q
#New -> MPC = 1.871138e-05*q+ 0.50

mpc_tax <- function(q) {1.871138e-05*q+ 0.50}

#Find the new market equilibrium point
# Set new supply to demand

q_agg_tax <- ((Q_aggb/Q_aggm)-0.50)/((1/Q_aggm)+.00001871138)
q_agg_tax <- (P_aggb-0.50)/(supply+-P_aggm)
q_agg_tax
# = 261333 gallons (261333.0349 w/ calculator)

#Find the new price at the equilibrium point
#q_aggregategph <- function(q){P_aggb+P_aggm*q}
p_agg_tax <- q_aggregategph(q_agg_tax)
p_agg_tax 
# = $5.3899


#Find the consumer surplus for high income
q_at_tax_h <- (5.3899-23.3914418)/(-0.0001297)
q_at_tax_h
#q = 138793.7
demand_eq_high(q_at_tax_h)

#Calculate the high demand CS at new price
height_tax_h <- 23.3914418 - 5.3899
base_tax_h <- 138793.7
cs_tax_h <- (1/2)*height_tax_h*base_tax_h 
cs_tax_h
# = $1249250

#Find the consumer surplus for low income
q_at_tax_l <- (5.3899-21.9908534)/(-0.0001355)
q_at_tax_l
#q = 122516.3

#Calculate the low demand CS at new price
height_tax_l <- 21.9908534 - 5.3899
base_tax_l <- 122516.3
cs_tax_l <- (1/2)*height_tax_l*base_tax_l
cs_tax_l
# = $1016944

#Calculate the producer surplus at new price
agg_height_ps_tax <- 5.3899
agg_base_ps_tax <- 261333
aggregate_ps_geom_tax <- (1/2)*agg_height_ps_tax*agg_base_ps_tax
aggregate_ps_geom_tax
# = $704279.5

#Calculate the environmental cost with the new tax
tec_tax <- (2*261333)
tec_tax
# = $522666

#Calculate the total revenue with the tax
#Calculate the price with new quantity at tax
rev_price <- mpcgph(q_agg_tax)
rev_price

#Calculate the revenue
rev_tax <- q_agg_tax*(p_agg_tax-rev_price)
rev_tax
# = $130666.5 

```



























```{r, echo=FALSE}


#Create a linear regression
demand_high_lmt <- lm(Price_Dollars ~ gas_df$Q_High_Gallons_per_Day, data = gas_df)
demand_high_lmt

demand_low_lmt <- lm(Price_Dollars ~ gas_df$Q_Low_Gallons_per_Day, data = gas_df)
demand_low_lmt



#Set Coefficients

#High Demand Coefficients
demand_high_lm$coefficients
bht = demand_high_lmt$coefficients[1]
mht = (demand_high_lmt$coefficients[2])

#High Demand Equation
#ph = bh - mh(q)
#ph = 23.3914418-0.0001297(q)

qhighAt <- (1/mht) # 1/slope or m for high income
qhighBt <- (bht/-mht) # intercept or b/ - slope or m for high income

#Low Demand Coefficients
demand_low_lmt$coefficients
blt = demand_low_lmt$coefficients[1]
mlt = (demand_low_lmt$coefficients[2])

#Low Demand Equation
#pl = bl - ml(q)
#pl = 21.9908534-0.0001355(q)

qlowAt <- (1/mlt) # 1/slope or m for low income
qlowBt <- (blt/-mht) # intercept or b/ - slope or m for low income



#Make Demand Curves
demand_eq_hight <- function(q) {23.3914418-0.0001297*q}
demand_eq_lowt <- function(q) {21.9908534-0.0001355*q}



#Find aggregate demands separately for quantity
Q_aggbt<- qlowBt + qhighBt # aggregate for intercept
Q_aggmt<- qlowAt + qhighAt # aggregate for slope



#Find aggregate demand separately for price
P_aggbt<- -Q_aggbt/Q_aggmt # aggregate for intercept
P_aggmt<- 1/Q_aggmt # aggregate for slope



# Find aggregate demand curve
q_aggregatet <- function(q){P_aggbt+P_aggm*qt}



#Find MPC (supply curve) by plugging in 5 for the aggregate demand curve
supplyt<- 5.50/((5.50-P_aggbt)/P_aggmt)
supplyt



# Find marginal external cost
mect <- function(y) {2}



# List out functions
demand_eq_highgpht <- function(q) {23.3914418-0.0001297*q}
demand_eq_lowgpht <- function(q) {21.9908534-0.0001355*q}
mpcgpht <- function(q) {supplyt*q}
mecgpht <- function(y) {2}
q_aggregategpht <- function(q){P_aggbt+P_aggmt*q}



# Set up data frame to optimum point
opt<- data.frame(x = c(0:267217.1), y = c(5))
x<- 70000:500000
demand_gpht <- ggplot(data.frame(x = c(70000:400000)), aes(x=x))+
  stat_function(fun=mpcgpht, geom = "line", color ="darkolivegreen3") +
  stat_function(fun=demand_eq_highgpht, geom="line", color ="red3") +
  stat_function(fun=demand_eq_lowgpht, geom="line", color ="goldenrod1") +
  stat_function(fun=q_aggregategpht, geom = "line", color ="darkorange3") +
  stat_function(fun=mecgpht, geom = "line", color ="chartreuse4") +
  xlab("\nQuantity (Gallons per Day)")+
  ylab("Price ($USD)\n")+
  ggtitle("Gas Market Under with a $0.50 Tax \n")+
  scale_y_continuous(limits = c(0,25), expand = c(0,0))+
  scale_x_continuous(limits = c(0,400000), expand = c(0,0), breaks = seq(0, 400000, 50000)) +
  theme_classic()

demand_gpht

```

